version: "3.2"

services:
  node-app:
    image: "webapp:${TAG}"
    command: npm start
    ports:
      - "3006:3000"
    networks:
      - appnetworkname
    depends_on:
      - db-mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db-mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3379:3306"
    volumes:
      - "mysql-data-node-app:/var/lib/mysql"
    networks:
    - appnetworkname

networks:
  appnetworkname:
    driver: bridge      

volumes:
    mysql-data-node-app:
